title: UgandaEMR User Manual
author: Monitoring and Evaluation Technical Support (METS) Program
theme: jekyll-theme-modernist
safe: true
gist:
  noscript: false
plugins:
  - jekyll-sitemap
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE